// Generated by GithubCopilot
// ============================================
// 10 - DECORATORS
// ============================================

// One example: a simple method logger decorator that wraps a method
// to log its calls with arguments and return value.

/**
 * A method decorator that logs calls with arguments and return value.
 * Requires "experimentalDecorators": true in tsconfig.json.
 */
function Log(
  _target: object,
  propertyKey: string,
  descriptor: PropertyDescriptor,
): void {
  const original = descriptor.value as (...args: unknown[]) => unknown;
  descriptor.value = function (...args: unknown[]) {
    console.log(`→ ${propertyKey}(${args.join(", ")})`);
    const result = original.apply(this, args);
    console.log(`← ${propertyKey} returned ${String(result)}`);
    return result;
  };
}

class MathService {
  @Log
  add(a: number, b: number): number {
    return a + b;
  }
}

const math = new MathService();
math.add(2, 3);
// → add(2, 3)
// ← add returned 5

/*
  KEY TAKEAWAYS:
  ✅ Decorators = reusable behavior attached to methods/classes
  ✅ Method decorator receives (target, propertyKey, descriptor)
  ✅ Wrap descriptor.value to intercept calls
  ✅ Requires "experimentalDecorators": true in tsconfig.json
  ✅ Common uses: logging, validation, auth, caching (NestJS, Angular)
*/
